// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[id].tsx";
import * as $1 from "./routes/create.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Header.tsx";
import * as $$1 from "./islands/Layout.tsx";
import * as $$2 from "./islands/Organization.tsx";

const manifest = {
  routes: {
    "./routes/[id].tsx": $0,
    "./routes/create.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Header.tsx": $$0,
    "./islands/Layout.tsx": $$1,
    "./islands/Organization.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
